version: '3.7'
services:
  hello-world-1:
    image: hello-world:latest
  hello-world-2:
    image: hello-world:latest
  hello-world-3:
    image: hello-world:latest
  haproxy:
    build: ./haproxy
    ports:
      - '80:8085'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - hello-world-1
      - hello-world-2
      - hello-world-3
